name: "Generate release & new package to NPM"

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Create Release
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });

  publish-package:
    name: Release package to Github packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@qumu'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FE_CI_BOT_TOKEN }}

      - run: npm run build

      - name: Use Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: 'npm'
          token: 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

      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken 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
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: 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
