name: "Lint, test and scan"
permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@qumu'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FE_CI_BOT_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:cov --workspace lib

      - name: SonarCloud Scan
        # Pinned to v6.0.0 but using SHA for safety - https://docs.github.com/en/actions/reference/security/secure-use#using-third-party-actions
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
